version: '2'
services:
  grafana:
    image: monstrenyatko/rpi-grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana:rw
    ports:
      - "3000:3000"
    restart: unless-stopped
volumes:
  grafana-data:
